# Description: test image
FROM busybox:latest
MAINTAINER "hellodemos.com"
COPY index.html /data/web/html/
COPY yum.repos.d /etc/yum.repos.d/
# 注：ADD 的<src> 是网上的nginx下载路径
ADD https://raw.githubusercontent.com/hewebgl3/dockerfile/master/add1/nginx-1.15.8.tar.gz /usr/local/src/